# Generated by Django 4.2.2 on 2023-06-25 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conferencesystem', '0002_alter_paper_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='conference',
        ),
        migrations.AlterField(
            model_name='author',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='author',
            name='conference',
            field=models.ManyToManyField(to='conferencesystem.conference'),
        ),
    ]
