# Generated by Django 4.2.2 on 2023-06-25 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferencesystem', '0003_remove_author_conference_alter_author_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='conference',
            new_name='conferences',
        ),
    ]
