# Generated by Django 4.2.2 on 2023-06-26 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conferencesystem', '0004_rename_conference_author_conferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chair',
            name='conference',
        ),
        migrations.AddField(
            model_name='chair',
            name='conferences',
            field=models.ManyToManyField(to='conferencesystem.conference'),
        ),
        migrations.AlterField(
            model_name='chair',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
