# Generated by Django 4.2.2 on 2023-06-27 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conferencesystem', '0005_remove_chair_conference_chair_conferences_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewer',
            name='conference',
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='conference',
            field=models.ManyToManyField(to='conferencesystem.conference'),
        ),
    ]
