# Generated by Django 4.2.2 on 2023-06-27 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferencesystem', '0006_remove_reviewer_conference_alter_reviewer_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewer',
            old_name='conference',
            new_name='conferences',
        ),
    ]
