# Generated by Django 4.2.2 on 2023-06-28 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferencesystem', '0008_alter_paper_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewer',
            name='conferences',
        ),
        migrations.AddField(
            model_name='reviewer',
            name='papers',
            field=models.ManyToManyField(to='conferencesystem.paper'),
        ),
    ]
