# Generated by Django 4.2.2 on 2023-06-28 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferencesystem', '0010_alter_review_score'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('paper', 'reviewer')},
        ),
    ]
